class BibleBookKey {
  final String english;
  final String chinese;
  final List<String> acronyms;

  const BibleBookKey(this.english, this.chinese, {required this.acronyms});

  String get displayString => '$chinese ($english) [${acronyms.join(', ')}]';

  static const bookKeys = [
    BibleBookKey('Genisis', '創世記', acronyms: ['創', 'Gen']),
    BibleBookKey('Exodus', '出埃及記', acronyms: ['出', 'Exo', 'Exod']),
    BibleBookKey('Leviticus', '利未記', acronyms: ['利', 'Lev']),
    BibleBookKey('Numbers', '民數記', acronyms: ['民', 'Num']),
    BibleBookKey('Deuteronomy', '申命記', acronyms: ['申', 'Deut']),
    BibleBookKey('Joshua', '約書亞記', acronyms: ['書', 'Josh']),
    BibleBookKey('Judges', '士師記', acronyms: ['士', 'Judg']),
    BibleBookKey('Ruth', '路得記', acronyms: ['得', 'Ruth']),
    BibleBookKey('1 Samuel', '撒母耳記上', acronyms: ['撒上', '1Sam']),
    BibleBookKey('2 Samuel', '撒母耳記下', acronyms: ['撒下', '2Sam']),
    BibleBookKey('1 Kings', '列王紀上', acronyms: ['王上', '1Kgs']),
    BibleBookKey('2 Kings', '列王紀下', acronyms: ['王下', '2Kgs']),
    BibleBookKey('1 Chronicles', '歷代志上', acronyms: ['代上', '1Chron']),
    BibleBookKey('2 Chronicles', '歷代志下', acronyms: ['代下', '2Chron']),
    BibleBookKey('Ezra', '以斯拉記', acronyms: ['拉', 'Ezra']),
    BibleBookKey('Nehemiah', '尼希米記', acronyms: ['尼', 'Neh']),
    BibleBookKey('Esther', '以斯貼記', acronyms: ['斯', 'Est']),
    BibleBookKey('Job', '約伯記', acronyms: ['伯', 'Job']),
    BibleBookKey('Psalm', '詩篇', acronyms: ['詩', 'Ps']),
    BibleBookKey('Proverbs', '箴言', acronyms: ['箴', 'Prov']),
    BibleBookKey('Ecclesiastes', '傳道書', acronyms: ['傳', 'Eccl']),
    BibleBookKey('Song of Songs', '雅歌', acronyms: ['歌', 'Song']),
    BibleBookKey('Isaiah', '以賽亞書', acronyms: ['賽', 'Isa']),
    BibleBookKey('Jeremiah', '耶利米書', acronyms: ['耶', 'Jer']),
    BibleBookKey('Lamentations', '耶利米哀歌', acronyms: ['哀', 'Lam']),
    BibleBookKey('Ezekiel', '以西結書', acronyms: ['結', 'Ezek']),
    BibleBookKey('Daniel', '但以理書', acronyms: ['但', 'Dan']),
    BibleBookKey('Hosea', '何西阿書', acronyms: ['何', 'Hos']),
    BibleBookKey('Joel', '約珥書', acronyms: ['珥', 'Joel']),
    BibleBookKey('Amos', '阿摩司書', acronyms: ['摩', 'Amos']),
    BibleBookKey('Obadiah', '俄巴底亞書', acronyms: ['俄', 'Obad']),
    BibleBookKey('Jonah', '約拿書', acronyms: ['拿', 'Jonah']),
    BibleBookKey('Micah', '彌迦書', acronyms: ['彌', 'Mic']),
    BibleBookKey('Nahum', '那鴻書', acronyms: ['鴻', 'Nah']),
    BibleBookKey('Habakkuk', '哈巴谷書', acronyms: ['哈', 'Hab']),
    BibleBookKey('Zephaniah', '西番雅書', acronyms: ['番', 'Zeph']),
    BibleBookKey('Haggai', '哈該書', acronyms: ['該', 'Hag']),
    BibleBookKey('Zechariah', '撒迦利亞書', acronyms: ['亞', 'Zech']),
    BibleBookKey('Malachi', '瑪拉基書', acronyms: ['瑪', 'Mal']),
    BibleBookKey('Matthew', '馬太福音', acronyms: ['太', 'Matt']),
    BibleBookKey('Mark', '馬可福音', acronyms: ['可', 'Mark']),
    BibleBookKey('Luke', '路加福音', acronyms: ['路', 'Luke']),
    BibleBookKey('John', '約翰福音', acronyms: ['約', 'John']),
    BibleBookKey('Acts', '使徒行傳', acronyms: ['徒', 'Acts']),
    BibleBookKey('Romans', '羅馬書', acronyms: ['羅', 'Rom']),
    BibleBookKey('1 Corinthians', '哥林多前書', acronyms: ['林前', '1Cor']),
    BibleBookKey('2 Corinthians', '哥林多後書', acronyms: ['林後', '2Cor']),
    BibleBookKey('Galatians', '加拉太書', acronyms: ['加', 'Gal']),
    BibleBookKey('Ephesians', '以弗所書', acronyms: ['弗', 'Eph']),
    BibleBookKey('Philippians', '腓立比書', acronyms: ['腓', 'Phil']),
    BibleBookKey('Colossians', '歌羅西書', acronyms: ['西', 'Col']),
    BibleBookKey('1 Thessalonians', '帖撒羅尼迦前書', acronyms: ['帖前', '1Thess']),
    BibleBookKey('2 Thessalonians', '帖撒羅尼迦後書', acronyms: ['帖後', '2Thess']),
    BibleBookKey('1 Timothy', '提摩太前書', acronyms: ['提前', '1Tim']),
    BibleBookKey('2 Timothy', '提摩太後書', acronyms: ['提後', '2Tim']),
    BibleBookKey('Titus', '提多書', acronyms: ['多', 'Titus']),
    BibleBookKey('Philemon', '腓利門書', acronyms: ['門', 'Philem']),
    BibleBookKey('Hebrews', '希伯來書', acronyms: ['來', 'Heb']),
    BibleBookKey('James', '雅各書', acronyms: ['雅', 'James']),
    BibleBookKey('1 Peter', '彼得前書', acronyms: ['彼前', '1Pet']),
    BibleBookKey('2 Peter', '彼得後書', acronyms: ['彼後', '2Pet']),
    BibleBookKey('1 John', '約翰一書', acronyms: ['約一', '1John']),
    BibleBookKey('2 John', '約翰二書', acronyms: ['約二', '2John']),
    BibleBookKey('3 John', '約翰三書', acronyms: ['約三', '3John']),
    BibleBookKey('Jude', '猶大書', acronyms: ['猶', 'Jude']),
    BibleBookKey('Revelation', '啟示錄', acronyms: ['啟', 'Rev']),
  ];
}
