// ignore_for_file: constant_identifier_names, unused_field

enum BibleBookEnum {
  Genisis,
  Exodus,
  Leviticus,
  Numbers,
  Deuteronomy,
  Joshua,
  Judges,
  Ruth,
  _1Samuel,
  _2Samuel,
  _1Kings,
  _2Kings,
  _1Chronicles,
  _2Chronicles,
  Ezra,
  Nehemiah,
  Esther,
  Job,
  Psalm,
  Proverbs,
  Ecclesiastes,
  SongOfSongs,
  Isaiah,
  Jeremiah,
  Lamentations,
  Ezekiel,
  Daniel,
  Hosea,
  Joel,
  Amos,
  Obadiah,
  Jonah,
  Micah,
  Nahum,
  Habakkuk,
  Zephaniah,
  Haggai,
  Zechariah,
  Malachi,
  Matthew,
  Mark,
  Luke,
  John,
  Acts,
  Romans,
  _1Corinthians,
  _2Corinthians,
  Galatians,
  Ephesians,
  Philippians,
  Colossians,
  _1Thessalonians,
  _2Thessalonians,
  _1Timothy,
  _2Timothy,
  Titus,
  Philemon,
  Hebrews,
  James,
  _1Peter,
  _2Peter,
  _1John,
  _2John,
  _3John,
  Jude,
  Revelation,
}

class BibleBookKey {
  final int chapterCount;
  final BibleBookEnum bookEnum;
  final String english;
  final String chinese;
  final List<String> acronyms;

  const BibleBookKey({
    required this.chapterCount,
    required this.bookEnum,
    required this.english,
    required this.chinese,
    required this.acronyms,
  });

  String get displayString => '$chinese ($english) [${acronyms.join(', ')}]';

  static const keys = [
    BibleBookKey(
      chapterCount: 50,
      bookEnum: BibleBookEnum.Genisis,
      english: 'Genisis',
      chinese: '創世記',
      acronyms: ['創', 'Gen'],
    ),
    BibleBookKey(
      chapterCount: 40,
      bookEnum: BibleBookEnum.Exodus,
      english: 'Exodus',
      chinese: '出埃及記',
      acronyms: ['出', 'Exo', 'Exod'],
    ),
    BibleBookKey(
      chapterCount: 27,
      bookEnum: BibleBookEnum.Leviticus,
      english: 'Leviticus',
      chinese: '利未記',
      acronyms: ['利', 'Lev'],
    ),
    BibleBookKey(
      chapterCount: 36,
      bookEnum: BibleBookEnum.Numbers,
      english: 'Numbers',
      chinese: '民數記',
      acronyms: ['民', 'Num'],
    ),
    BibleBookKey(
      chapterCount: 34,
      bookEnum: BibleBookEnum.Deuteronomy,
      english: 'Deuteronomy',
      chinese: '申命記',
      acronyms: ['申', 'Deut'],
    ),
    BibleBookKey(
      chapterCount: 24,
      bookEnum: BibleBookEnum.Joshua,
      english: 'Joshua',
      chinese: '約書亞記',
      acronyms: ['書', 'Josh'],
    ),
    BibleBookKey(
      chapterCount: 21,
      bookEnum: BibleBookEnum.Judges,
      english: 'Judges',
      chinese: '士師記',
      acronyms: ['士', 'Judg'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum.Ruth,
      english: 'Ruth',
      chinese: '路得記',
      acronyms: ['得', 'Ruth'],
    ),
    BibleBookKey(
      chapterCount: 31,
      bookEnum: BibleBookEnum._1Samuel,
      english: '1 Samuel',
      chinese: '撒母耳記上',
      acronyms: ['撒上', '1Sam'],
    ),
    BibleBookKey(
      chapterCount: 24,
      bookEnum: BibleBookEnum._2Samuel,
      english: '2 Samuel',
      chinese: '撒母耳記下',
      acronyms: ['撒下', '2Sam'],
    ),
    BibleBookKey(
      chapterCount: 22,
      bookEnum: BibleBookEnum._1Kings,
      english: '1 Kings',
      chinese: '列王紀上',
      acronyms: ['王上', '1Kgs'],
    ),
    BibleBookKey(
      chapterCount: 25,
      bookEnum: BibleBookEnum._2Kings,
      english: '2 Kings',
      chinese: '列王紀下',
      acronyms: ['王下', '2Kgs'],
    ),
    BibleBookKey(
      chapterCount: 29,
      bookEnum: BibleBookEnum._1Chronicles,
      english: '1 Chronicles',
      chinese: '歷代志上',
      acronyms: ['代上', '1Chron'],
    ),
    BibleBookKey(
      chapterCount: 36,
      bookEnum: BibleBookEnum._2Chronicles,
      english: '2 Chronicles',
      chinese: '歷代志下',
      acronyms: ['代下', '2Chron'],
    ),
    BibleBookKey(
      chapterCount: 10,
      bookEnum: BibleBookEnum.Ezra,
      english: 'Ezra',
      chinese: '以斯拉記',
      acronyms: ['拉', 'Ezra'],
    ),
    BibleBookKey(
      chapterCount: 13,
      bookEnum: BibleBookEnum.Nehemiah,
      english: 'Nehemiah',
      chinese: '尼希米記',
      acronyms: ['尼', 'Neh'],
    ),
    BibleBookKey(
      chapterCount: 10,
      bookEnum: BibleBookEnum.Esther,
      english: 'Esther',
      chinese: '以斯貼記',
      acronyms: ['斯', 'Est'],
    ),
    BibleBookKey(
      chapterCount: 42,
      bookEnum: BibleBookEnum.Job,
      english: 'Job',
      chinese: '約伯記',
      acronyms: ['伯', 'Job'],
    ),
    BibleBookKey(
      chapterCount: 150,
      bookEnum: BibleBookEnum.Psalm,
      english: 'Psalm',
      chinese: '詩篇',
      acronyms: ['詩', 'Ps'],
    ),
    BibleBookKey(
      chapterCount: 31,
      bookEnum: BibleBookEnum.Proverbs,
      english: 'Proverbs',
      chinese: '箴言',
      acronyms: ['箴', 'Prov'],
    ),
    BibleBookKey(
      chapterCount: 12,
      bookEnum: BibleBookEnum.Ecclesiastes,
      english: 'Ecclesiastes',
      chinese: '傳道書',
      acronyms: ['傳', 'Eccl'],
    ),
    BibleBookKey(
      chapterCount: 8,
      bookEnum: BibleBookEnum.SongOfSongs,
      english: 'Song of Songs',
      chinese: '雅歌',
      acronyms: ['歌', 'Song'],
    ),
    BibleBookKey(
      chapterCount: 66,
      bookEnum: BibleBookEnum.Isaiah,
      english: 'Isaiah',
      chinese: '以賽亞書',
      acronyms: ['賽', 'Isa'],
    ),
    BibleBookKey(
      chapterCount: 52,
      bookEnum: BibleBookEnum.Jeremiah,
      english: 'Jeremiah',
      chinese: '耶利米書',
      acronyms: ['耶', 'Jer'],
    ),
    BibleBookKey(
      chapterCount: 5,
      bookEnum: BibleBookEnum.Lamentations,
      english: 'Lamentations',
      chinese: '耶利米哀歌',
      acronyms: ['哀', 'Lam'],
    ),
    BibleBookKey(
      chapterCount: 48,
      bookEnum: BibleBookEnum.Ezekiel,
      english: 'Ezekiel',
      chinese: '以西結書',
      acronyms: ['結', 'Ezek'],
    ),
    BibleBookKey(
      chapterCount: 12,
      bookEnum: BibleBookEnum.Daniel,
      english: 'Daniel',
      chinese: '但以理書',
      acronyms: ['但', 'Dan'],
    ),
    BibleBookKey(
      chapterCount: 14,
      bookEnum: BibleBookEnum.Hosea,
      english: 'Hosea',
      chinese: '何西阿書',
      acronyms: ['何', 'Hos'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum.Joel,
      english: 'Joel',
      chinese: '約珥書',
      acronyms: ['珥', 'Joel'],
    ),
    BibleBookKey(
      chapterCount: 9,
      bookEnum: BibleBookEnum.Amos,
      english: 'Amos',
      chinese: '阿摩司書',
      acronyms: ['摩', 'Amos'],
    ),
    BibleBookKey(
      chapterCount: 1,
      bookEnum: BibleBookEnum.Obadiah,
      english: 'Obadiah',
      chinese: '俄巴底亞書',
      acronyms: ['俄', 'Obad'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum.Jonah,
      english: 'Jonah',
      chinese: '約拿書',
      acronyms: ['拿', 'Jonah'],
    ),
    BibleBookKey(
      chapterCount: 7,
      bookEnum: BibleBookEnum.Micah,
      english: 'Micah',
      chinese: '彌迦書',
      acronyms: ['彌', 'Mic'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum.Nahum,
      english: 'Nahum',
      chinese: '那鴻書',
      acronyms: ['鴻', 'Nah'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum.Habakkuk,
      english: 'Habakkuk',
      chinese: '哈巴谷書',
      acronyms: ['哈', 'Hab'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum.Zephaniah,
      english: 'Zephaniah',
      chinese: '西番雅書',
      acronyms: ['番', 'Zeph'],
    ),
    BibleBookKey(
      chapterCount: 2,
      bookEnum: BibleBookEnum.Haggai,
      english: 'Haggai',
      chinese: '哈該書',
      acronyms: ['該', 'Hag'],
    ),
    BibleBookKey(
      chapterCount: 14,
      bookEnum: BibleBookEnum.Zechariah,
      english: 'Zechariah',
      chinese: '撒迦利亞書',
      acronyms: ['亞', 'Zech'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum.Malachi,
      english: 'Malachi',
      chinese: '瑪拉基書',
      acronyms: ['瑪', 'Mal'],
    ),
    BibleBookKey(
      chapterCount: 28,
      bookEnum: BibleBookEnum.Matthew,
      english: 'Matthew',
      chinese: '馬太福音',
      acronyms: ['太', 'Matt'],
    ),
    BibleBookKey(
      chapterCount: 16,
      bookEnum: BibleBookEnum.Mark,
      english: 'Mark',
      chinese: '馬可福音',
      acronyms: ['可', 'Mark'],
    ),
    BibleBookKey(
      chapterCount: 24,
      bookEnum: BibleBookEnum.Luke,
      english: 'Luke',
      chinese: '路加福音',
      acronyms: ['路', 'Luke'],
    ),
    BibleBookKey(
      chapterCount: 21,
      bookEnum: BibleBookEnum.John,
      english: 'John',
      chinese: '約翰福音',
      acronyms: ['約', 'John'],
    ),
    BibleBookKey(
      chapterCount: 28,
      bookEnum: BibleBookEnum.Acts,
      english: 'Acts',
      chinese: '使徒行傳',
      acronyms: ['徒', 'Acts'],
    ),
    BibleBookKey(
      chapterCount: 16,
      bookEnum: BibleBookEnum.Romans,
      english: 'Romans',
      chinese: '羅馬書',
      acronyms: ['羅', 'Rom'],
    ),
    BibleBookKey(
      chapterCount: 16,
      bookEnum: BibleBookEnum._1Corinthians,
      english: '1 Corinthians',
      chinese: '哥林多前書',
      acronyms: ['林前', '1Cor'],
    ),
    BibleBookKey(
      chapterCount: 13,
      bookEnum: BibleBookEnum._2Corinthians,
      english: '2 Corinthians',
      chinese: '哥林多後書',
      acronyms: ['林後', '2Cor'],
    ),
    BibleBookKey(
      chapterCount: 6,
      bookEnum: BibleBookEnum.Galatians,
      english: 'Galatians',
      chinese: '加拉太書',
      acronyms: ['加', 'Gal'],
    ),
    BibleBookKey(
      chapterCount: 6,
      bookEnum: BibleBookEnum.Ephesians,
      english: 'Ephesians',
      chinese: '以弗所書',
      acronyms: ['弗', 'Eph'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum.Philippians,
      english: 'Philippians',
      chinese: '腓立比書',
      acronyms: ['腓', 'Phil'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum.Colossians,
      english: 'Colossians',
      chinese: '歌羅西書',
      acronyms: ['西', 'Col'],
    ),
    BibleBookKey(
      chapterCount: 5,
      bookEnum: BibleBookEnum._1Thessalonians,
      english: '1 Thessalonians',
      chinese: '帖撒羅尼迦前書',
      acronyms: ['帖前', '1Thess'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum._2Thessalonians,
      english: '2 Thessalonians',
      chinese: '帖撒羅尼迦後書',
      acronyms: ['帖後', '2Thess'],
    ),
    BibleBookKey(
      chapterCount: 6,
      bookEnum: BibleBookEnum._1Timothy,
      english: '1 Timothy',
      chinese: '提摩太前書',
      acronyms: ['提前', '1Tim'],
    ),
    BibleBookKey(
      chapterCount: 4,
      bookEnum: BibleBookEnum._2Timothy,
      english: '2 Timothy',
      chinese: '提摩太後書',
      acronyms: ['提後', '2Tim'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum.Titus,
      english: 'Titus',
      chinese: '提多書',
      acronyms: ['多', 'Titus'],
    ),
    BibleBookKey(
      chapterCount: 1,
      bookEnum: BibleBookEnum.Philemon,
      english: 'Philemon',
      chinese: '腓利門書',
      acronyms: ['門', 'Philem'],
    ),
    BibleBookKey(
      chapterCount: 13,
      bookEnum: BibleBookEnum.Hebrews,
      english: 'Hebrews',
      chinese: '希伯來書',
      acronyms: ['來', 'Heb'],
    ),
    BibleBookKey(
      chapterCount: 5,
      bookEnum: BibleBookEnum.James,
      english: 'James',
      chinese: '雅各書',
      acronyms: ['雅', 'James'],
    ),
    BibleBookKey(
      chapterCount: 5,
      bookEnum: BibleBookEnum._1Peter,
      english: '1 Peter',
      chinese: '彼得前書',
      acronyms: ['彼前', '1Pet'],
    ),
    BibleBookKey(
      chapterCount: 3,
      bookEnum: BibleBookEnum._2Peter,
      english: '2 Peter',
      chinese: '彼得後書',
      acronyms: ['彼後', '2Pet'],
    ),
    BibleBookKey(
      chapterCount: 5,
      bookEnum: BibleBookEnum._1John,
      english: '1 John',
      chinese: '約翰一書',
      acronyms: ['約一', '1John'],
    ),
    BibleBookKey(
      chapterCount: 1,
      bookEnum: BibleBookEnum._2John,
      english: '2 John',
      chinese: '約翰二書',
      acronyms: ['約二', '2John'],
    ),
    BibleBookKey(
      chapterCount: 1,
      bookEnum: BibleBookEnum._3John,
      english: '3 John',
      chinese: '約翰三書',
      acronyms: ['約三', '3John'],
    ),
    BibleBookKey(
      chapterCount: 1,
      bookEnum: BibleBookEnum.Jude,
      english: 'Jude',
      chinese: '猶大書',
      acronyms: ['猶', 'Jude'],
    ),
    BibleBookKey(
      chapterCount: 22,
      bookEnum: BibleBookEnum.Revelation,
      english: 'Revelation',
      chinese: '啟示錄',
      acronyms: ['啟', 'Rev'],
    ),
  ];
}
